{
  "compatibilityLevel": 1600,
  "model": {
    "annotations": [
      {"name": "PBI_QueryOrder", "value": "[\"SAFETY_INCIDENTS\",\"ABSENCE_RECORDS\",\"EMPLOYEES\",\"DimMonth\"]"},
      {"name": "__PBI_TimeIntelligenceEnabled", "value": "0"}
    ],
    "culture": "en-US",
    "dataAccessOptions": {"legacyRedirects": true, "returnErrorValuesAsNull": true},
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "relationships": [
      {"name": "rel_inc_emp", "fromColumn": "EMPLOYEE_ID", "fromTable": "SAFETY_INCIDENTS", "toColumn": "EMPLOYEE_ID", "toTable": "EMPLOYEES"},
      {"name": "rel_abs_emp", "fromColumn": "EMPLOYEE_ID", "fromTable": "ABSENCE_RECORDS", "toColumn": "EMPLOYEE_ID", "toTable": "EMPLOYEES"}
    ],
    "tables": [
      {
        "name": "SAFETY_INCIDENTS",
        "columns": [
          {"name": "INCIDENT_ID", "dataType": "string", "lineageTag": "f08-inc-id", "sourceColumn": "INCIDENT_ID", "summarizeBy": "none"},
          {"name": "EMPLOYEE_ID", "dataType": "string", "lineageTag": "f08-inc-emp", "sourceColumn": "EMPLOYEE_ID", "summarizeBy": "none"},
          {"name": "DATE", "dataType": "dateTime", "formatString": "Long Date", "lineageTag": "f08-inc-date", "sourceColumn": "DATE", "summarizeBy": "none"},
          {"name": "LOCATION", "dataType": "string", "lineageTag": "f08-inc-loc", "sourceColumn": "LOCATION", "summarizeBy": "none"},
          {"name": "DEPARTMENT", "dataType": "string", "lineageTag": "f08-inc-dept", "sourceColumn": "DEPARTMENT", "summarizeBy": "none"},
          {"name": "INCIDENT_TYPE", "dataType": "string", "lineageTag": "f08-inc-type", "sourceColumn": "INCIDENT_TYPE", "summarizeBy": "none"},
          {"name": "SEVERITY", "dataType": "string", "lineageTag": "f08-inc-sev", "sourceColumn": "SEVERITY", "summarizeBy": "none"},
          {"name": "OVERTIME_ON_DAY", "dataType": "boolean", "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"", "lineageTag": "f08-inc-ot", "sourceColumn": "OVERTIME_ON_DAY", "summarizeBy": "none"},
          {"name": "HOURS_WORKED_BEFORE_INCIDENT", "dataType": "double", "lineageTag": "f08-inc-hwbi", "sourceColumn": "HOURS_WORKED_BEFORE_INCIDENT", "summarizeBy": "sum"},
          {
            "name": "MonthKey",
            "type": "calculated",
            "expression": "YEAR(SAFETY_INCIDENTS[DATE]) * 100 + MONTH(SAFETY_INCIDENTS[DATE])",
            "dataType": "int64",
            "lineageTag": "f08-inc-mk",
            "summarizeBy": "none"
          },
          {
            "name": "Month Start",
            "type": "calculated",
            "expression": "DATE(YEAR(SAFETY_INCIDENTS[DATE]), MONTH(SAFETY_INCIDENTS[DATE]), 1)",
            "dataType": "dateTime",
            "formatString": "mmm yyyy",
            "lineageTag": "f08-inc-mstart",
            "summarizeBy": "none"
          },
          {
            "name": "Week Of Year",
            "type": "calculated",
            "expression": "WEEKNUM(SAFETY_INCIDENTS[DATE], 2)",
            "dataType": "int64",
            "lineageTag": "f08-inc-wk",
            "summarizeBy": "none"
          },
          {
            "name": "Severity Weight",
            "type": "calculated",
            "expression": "SWITCH(SAFETY_INCIDENTS[SEVERITY], \"Critical\", 4, \"High\", 3, \"Medium\", 2, \"Low\", 1, 0)",
            "dataType": "int64",
            "lineageTag": "f08-inc-sw",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f08-tbl-inc",
        "measures": [
          {"name": "Incident Count", "expression": "DISTINCTCOUNT(SAFETY_INCIDENTS[INCIDENT_ID])", "formatString": "0", "lineageTag": "f08-m-inccount"},
          {"name": "Weighted Severity", "expression": "SUMX(SAFETY_INCIDENTS, SAFETY_INCIDENTS[Severity Weight])", "formatString": "0", "lineageTag": "f08-m-wsev"},
          {"name": "Avg Fatigue Hours", "expression": "AVERAGE(SAFETY_INCIDENTS[HOURS_WORKED_BEFORE_INCIDENT])", "formatString": "0.0", "lineageTag": "f08-m-fatigue"},
          {
            "name": "Incidents Prev Month",
            "expression": "CALCULATE([Incident Count], OFFSET(-1, ALLSELECTED(SAFETY_INCIDENTS[MonthKey]), ORDERBY(SAFETY_INCIDENTS[MonthKey], ASC)))",
            "formatString": "0",
            "lineageTag": "f08-m-incprev"
          },
          {
            "name": "Incident MoM Delta",
            "expression": "[Incident Count] - [Incidents Prev Month]",
            "formatString": "+0;-0;0",
            "lineageTag": "f08-m-incmom"
          },
          {
            "name": "Incident Rolling 3mo",
            "expression": "CALCULATE([Incident Count], WINDOW(-2, REL, 0, REL, ALLSELECTED(SAFETY_INCIDENTS[MonthKey]), ORDERBY(SAFETY_INCIDENTS[MonthKey], ASC)))",
            "formatString": "0",
            "lineageTag": "f08-m-incroll3"
          },
          {
            "name": "Month Rank By Incidents",
            "expression": "RANK(DENSE, ALLSELECTED(SAFETY_INCIDENTS[MonthKey]), ORDERBY([Incident Count], DESC))",
            "formatString": "0",
            "lineageTag": "f08-m-monthrank"
          },
          {
            "name": "Worst Month Incidents",
            "expression": "CALCULATE([Incident Count], INDEX(1, ALLSELECTED(SAFETY_INCIDENTS[MonthKey]), ORDERBY([Incident Count], DESC)))",
            "formatString": "0",
            "lineageTag": "f08-m-worstmonth"
          },
          {
            "name": "Overtime Incident Rate",
            "expression": "DIVIDE(CALCULATE([Incident Count], KEEPFILTERS(SAFETY_INCIDENTS[OVERTIME_ON_DAY] = TRUE())), [Incident Count])",
            "formatString": "0.0%",
            "lineageTag": "f08-m-otrate"
          },
          {
            "name": "Incident Pct of All Depts",
            "expression": "DIVIDE([Incident Count], CALCULATE([Incident Count], REMOVEFILTERS(SAFETY_INCIDENTS[DEPARTMENT])))",
            "formatString": "0.0%",
            "lineageTag": "f08-m-incpctdept"
          },
          {
            "name": "Drill Scope Label",
            "expression": "IF(ISINSCOPE(SAFETY_INCIDENTS[INCIDENT_TYPE]), \"By Type\", IF(ISINSCOPE(SAFETY_INCIDENTS[DEPARTMENT]), \"By Dept\", \"Total\"))",
            "lineageTag": "f08-m-drillscope"
          }
        ],
        "partitions": [
          {"name": "SAFETY_INCIDENTS", "mode": "import", "source": {"expression": ["let", "  Source = Snowflake.Databases(\"ymb68310.snowflakecomputing.com\", \"SIGMA_WH\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = \"2.0\"]),", "  #\"Navigation 1\" = Source{[Name = \"CSA\", Kind = \"Database\"]}[Data],", "  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TJ\", Kind = \"Schema\"]}[Data],", "  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"SAFETY_INCIDENTS\", Kind = \"Table\"]}[Data]", "in", "  #\"Navigation 3\""], "type": "m"}}
        ]
      },
      {
        "name": "ABSENCE_RECORDS",
        "columns": [
          {"name": "ABSENCE_ID", "dataType": "string", "lineageTag": "f08-abs-id", "sourceColumn": "ABSENCE_ID", "summarizeBy": "none"},
          {"name": "EMPLOYEE_ID", "dataType": "string", "lineageTag": "f08-abs-emp", "sourceColumn": "EMPLOYEE_ID", "summarizeBy": "none"},
          {"name": "DATE", "dataType": "dateTime", "formatString": "Long Date", "lineageTag": "f08-abs-date", "sourceColumn": "DATE", "summarizeBy": "none"},
          {"name": "ABSENCE_TYPE", "dataType": "string", "lineageTag": "f08-abs-type", "sourceColumn": "ABSENCE_TYPE", "summarizeBy": "none"},
          {"name": "HOURS", "dataType": "double", "lineageTag": "f08-abs-hours", "sourceColumn": "HOURS", "summarizeBy": "sum"},
          {"name": "DAY_OF_WEEK", "dataType": "string", "lineageTag": "f08-abs-dow", "sourceColumn": "DAY_OF_WEEK", "summarizeBy": "none"},
          {"name": "DEPARTMENT", "dataType": "string", "lineageTag": "f08-abs-dept", "sourceColumn": "DEPARTMENT", "summarizeBy": "none"},
          {
            "name": "MonthKey",
            "type": "calculated",
            "expression": "YEAR(ABSENCE_RECORDS[DATE]) * 100 + MONTH(ABSENCE_RECORDS[DATE])",
            "dataType": "int64",
            "lineageTag": "f08-abs-mk",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f08-tbl-abs",
        "measures": [
          {"name": "Total Absence Hours", "expression": "SUM(ABSENCE_RECORDS[HOURS])", "formatString": "#,0.0", "lineageTag": "f08-m-abshours"},
          {
            "name": "Absence Hours Prev Month",
            "expression": "CALCULATE([Total Absence Hours], OFFSET(-1, ALLSELECTED(ABSENCE_RECORDS[MonthKey]), ORDERBY(ABSENCE_RECORDS[MonthKey], ASC)))",
            "formatString": "#,0.0",
            "lineageTag": "f08-m-absprev"
          },
          {
            "name": "Absence Hours In Incident Depts",
            "expression": "VAR IncDepts = CALCULATETABLE(VALUES(SAFETY_INCIDENTS[DEPARTMENT]), ALL(SAFETY_INCIDENTS))\nRETURN CALCULATE([Total Absence Hours], TREATAS(IncDepts, ABSENCE_RECORDS[DEPARTMENT]))",
            "formatString": "#,0.0",
            "lineageTag": "f08-m-absincdept"
          }
        ],
        "partitions": [
          {"name": "ABSENCE_RECORDS", "mode": "import", "source": {"expression": ["let", "  Source = Snowflake.Databases(\"ymb68310.snowflakecomputing.com\", \"SIGMA_WH\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = \"2.0\"]),", "  #\"Navigation 1\" = Source{[Name = \"CSA\", Kind = \"Database\"]}[Data],", "  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TJ\", Kind = \"Schema\"]}[Data],", "  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"ABSENCE_RECORDS\", Kind = \"Table\"]}[Data]", "in", "  #\"Navigation 3\""], "type": "m"}}
        ]
      },
      {
        "name": "EMPLOYEES",
        "columns": [
          {"name": "EMPLOYEE_ID", "dataType": "string", "lineageTag": "f08-emp-id", "sourceColumn": "EMPLOYEE_ID", "summarizeBy": "none"},
          {"name": "DEPARTMENT", "dataType": "string", "lineageTag": "f08-emp-dept", "sourceColumn": "DEPARTMENT", "summarizeBy": "none"},
          {"name": "SHIFT", "dataType": "string", "lineageTag": "f08-emp-shift", "sourceColumn": "SHIFT", "summarizeBy": "none"},
          {"name": "STATUS", "dataType": "string", "lineageTag": "f08-emp-status", "sourceColumn": "STATUS", "summarizeBy": "none"}
        ],
        "lineageTag": "f08-tbl-emp",
        "measures": [
          {"name": "Headcount", "expression": "COUNTROWS(EMPLOYEES)", "formatString": "0", "lineageTag": "f08-m-hc"},
          {"name": "Incidents Per 100 Heads", "expression": "DIVIDE([Incident Count], [Headcount]) * 100", "formatString": "0.0", "lineageTag": "f08-m-incper100"}
        ],
        "partitions": [
          {"name": "EMPLOYEES", "mode": "import", "source": {"expression": ["let", "  Source = Snowflake.Databases(\"ymb68310.snowflakecomputing.com\", \"SIGMA_WH\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = \"2.0\"]),", "  #\"Navigation 1\" = Source{[Name = \"CSA\", Kind = \"Database\"]}[Data],", "  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TJ\", Kind = \"Schema\"]}[Data],", "  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"EMPLOYEES\", Kind = \"Table\"]}[Data]", "in", "  #\"Navigation 3\""], "type": "m"}}
        ]
      },
      {
        "name": "DimMonth",
        "columns": [
          {"name": "MonthKey", "dataType": "int64", "isKey": true, "type": "calculatedTableColumn", "sourceColumn": "MonthKey", "lineageTag": "f08-dm-mk", "summarizeBy": "none"},
          {"name": "MonthLabel", "dataType": "string", "type": "calculatedTableColumn", "sourceColumn": "MonthLabel", "lineageTag": "f08-dm-lbl", "summarizeBy": "none", "sortByColumn": "MonthKey"},
          {"name": "MonthEnd", "dataType": "dateTime", "formatString": "Short Date", "type": "calculatedTableColumn", "sourceColumn": "MonthEnd", "lineageTag": "f08-dm-end", "summarizeBy": "none"}
        ],
        "lineageTag": "f08-tbl-dimmonth",
        "partitions": [
          {
            "name": "DimMonth",
            "mode": "import",
            "source": {
              "expression": "SELECTCOLUMNS(ADDCOLUMNS(GENERATESERIES(0, 35, 1), \"_d\", EDATE(DATE(2024,1,1), [Value])), \"MonthKey\", YEAR([_d]) * 100 + MONTH([_d]), \"MonthLabel\", FORMAT([_d], \"MMM YYYY\"), \"MonthEnd\", EOMONTH([_d], 0))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}
