{
  "compatibilityLevel": 1600,
  "model": {
    "annotations": [
      {"name": "PBI_QueryOrder", "value": "[\"EMPLOYEES\",\"ABSENCE_RECORDS\",\"SAFETY_INCIDENTS\"]"}
    ],
    "culture": "en-US",
    "dataAccessOptions": {"legacyRedirects": true, "returnErrorValuesAsNull": true},
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {"name": "rel_absence_emp", "fromColumn": "EMPLOYEE_ID", "fromTable": "ABSENCE_RECORDS", "toColumn": "EMPLOYEE_ID", "toTable": "EMPLOYEES"},
      {"name": "rel_incident_emp", "fromColumn": "EMPLOYEE_ID", "fromTable": "SAFETY_INCIDENTS", "toColumn": "EMPLOYEE_ID", "toTable": "EMPLOYEES"}
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "EMPLOYEES",
        "columns": [
          {"name": "EMPLOYEE_ID", "dataType": "string", "lineageTag": "f03-emp-id", "sourceColumn": "EMPLOYEE_ID", "summarizeBy": "none"},
          {"name": "DEPARTMENT", "dataType": "string", "lineageTag": "f03-emp-dept", "sourceColumn": "DEPARTMENT", "summarizeBy": "none"},
          {"name": "LOCATION", "dataType": "string", "lineageTag": "f03-emp-loc", "sourceColumn": "LOCATION", "summarizeBy": "none"},
          {"name": "ANNUAL_SALARY", "dataType": "double", "lineageTag": "f03-emp-sal", "sourceColumn": "ANNUAL_SALARY", "summarizeBy": "sum"},
          {"name": "STATUS", "dataType": "string", "lineageTag": "f03-emp-status", "sourceColumn": "STATUS", "summarizeBy": "none"},
          {"name": "EMPLOYMENT_TYPE", "dataType": "string", "lineageTag": "f03-emp-et", "sourceColumn": "EMPLOYMENT_TYPE", "summarizeBy": "none"}
        ],
        "lineageTag": "f03-tbl-emp",
        "measures": [
          {"name": "Total Salary", "expression": "SUM(EMPLOYEES[ANNUAL_SALARY])", "formatString": "\\$#,0", "lineageTag": "f03-m-totsal"},
          {"name": "Avg Salary", "expression": "AVERAGE(EMPLOYEES[ANNUAL_SALARY])", "formatString": "\\$#,0", "lineageTag": "f03-m-avgsal"},
          {"name": "Salary Pct of Total", "expression": "DIVIDE([Total Salary], CALCULATE([Total Salary], ALL(EMPLOYEES)))", "formatString": "0.0%", "lineageTag": "f03-m-salpct"},
          {"name": "Salary Pct of Dept", "expression": "DIVIDE([Total Salary], CALCULATE([Total Salary], ALLEXCEPT(EMPLOYEES, EMPLOYEES[DEPARTMENT])))", "formatString": "0.0%", "lineageTag": "f03-m-salpctdept"},
          {"name": "Company Avg Salary", "expression": "CALCULATE(AVERAGE(EMPLOYEES[ANNUAL_SALARY]), ALL(EMPLOYEES))", "formatString": "\\$#,0", "lineageTag": "f03-m-coavgsal"},
          {"name": "Avg Salary vs Dept", "expression": "[Avg Salary] - CALCULATE(AVERAGE(EMPLOYEES[ANNUAL_SALARY]), ALLEXCEPT(EMPLOYEES, EMPLOYEES[DEPARTMENT]))", "formatString": "\\$#,0", "lineageTag": "f03-m-avgvsdept"},
          {"name": "High Earner Count", "expression": "CALCULATE(COUNTROWS(EMPLOYEES), FILTER(EMPLOYEES, EMPLOYEES[ANNUAL_SALARY] > 100000))", "formatString": "0", "lineageTag": "f03-m-highearn"},
          {"name": "Above Avg Earner Count", "expression": "CALCULATE(COUNTROWS(EMPLOYEES), FILTER(EMPLOYEES, EMPLOYEES[ANNUAL_SALARY] > [Company Avg Salary]))", "formatString": "0", "lineageTag": "f03-m-aboveavg"},
          {"name": "Active FullTime Salary", "expression": "CALCULATE(SUM(EMPLOYEES[ANNUAL_SALARY]), EMPLOYEES[STATUS] = \"Active\", EMPLOYEES[EMPLOYMENT_TYPE] = \"Full-Time\")", "formatString": "\\$#,0", "lineageTag": "f03-m-activeft"}
        ],
        "partitions": [
          {"name": "EMPLOYEES", "mode": "import", "source": {"expression": ["let", "  Source = Snowflake.Databases(\"ymb68310.snowflakecomputing.com\", \"SIGMA_WH\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = \"2.0\"]),", "  #\"Navigation 1\" = Source{[Name = \"CSA\", Kind = \"Database\"]}[Data],", "  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TJ\", Kind = \"Schema\"]}[Data],", "  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"EMPLOYEES\", Kind = \"Table\"]}[Data]", "in", "  #\"Navigation 3\""], "type": "m"}}
        ]
      },
      {
        "name": "ABSENCE_RECORDS",
        "columns": [
          {"name": "ABSENCE_ID", "dataType": "string", "lineageTag": "f03-abs-id", "sourceColumn": "ABSENCE_ID", "summarizeBy": "none"},
          {"name": "EMPLOYEE_ID", "dataType": "string", "lineageTag": "f03-abs-emp", "sourceColumn": "EMPLOYEE_ID", "summarizeBy": "none"},
          {"name": "ABSENCE_TYPE", "dataType": "string", "lineageTag": "f03-abs-type", "sourceColumn": "ABSENCE_TYPE", "summarizeBy": "none"},
          {"name": "HOURS", "dataType": "double", "lineageTag": "f03-abs-hours", "sourceColumn": "HOURS", "summarizeBy": "sum"},
          {"name": "DEPARTMENT", "dataType": "string", "lineageTag": "f03-abs-dept", "sourceColumn": "DEPARTMENT", "summarizeBy": "none"}
        ],
        "lineageTag": "f03-tbl-abs",
        "measures": [
          {"name": "Total Absence Hours", "expression": "SUM(ABSENCE_RECORDS[HOURS])", "formatString": "#,0.0", "lineageTag": "f03-m-abshours"},
          {"name": "Absence Hours Pct of Total", "expression": "DIVIDE(SUM(ABSENCE_RECORDS[HOURS]), CALCULATE(SUM(ABSENCE_RECORDS[HOURS]), ALL(ABSENCE_RECORDS)))", "formatString": "0.0%", "lineageTag": "f03-m-abspct"},
          {"name": "Sick Hours", "expression": "CALCULATE(SUM(ABSENCE_RECORDS[HOURS]), ABSENCE_RECORDS[ABSENCE_TYPE] = \"Sick\")", "formatString": "#,0.0", "lineageTag": "f03-m-sickhours"},
          {"name": "Long Absence Hours", "expression": "CALCULATE(SUM(ABSENCE_RECORDS[HOURS]), FILTER(ABSENCE_RECORDS, ABSENCE_RECORDS[HOURS] >= 8))", "formatString": "#,0.0", "lineageTag": "f03-m-longabs"}
        ],
        "partitions": [
          {"name": "ABSENCE_RECORDS", "mode": "import", "source": {"expression": ["let", "  Source = Snowflake.Databases(\"ymb68310.snowflakecomputing.com\", \"SIGMA_WH\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = \"2.0\"]),", "  #\"Navigation 1\" = Source{[Name = \"CSA\", Kind = \"Database\"]}[Data],", "  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TJ\", Kind = \"Schema\"]}[Data],", "  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"ABSENCE_RECORDS\", Kind = \"Table\"]}[Data]", "in", "  #\"Navigation 3\""], "type": "m"}}
        ]
      },
      {
        "name": "SAFETY_INCIDENTS",
        "columns": [
          {"name": "INCIDENT_ID", "dataType": "string", "lineageTag": "f03-inc-id", "sourceColumn": "INCIDENT_ID", "summarizeBy": "none"},
          {"name": "EMPLOYEE_ID", "dataType": "string", "lineageTag": "f03-inc-emp", "sourceColumn": "EMPLOYEE_ID", "summarizeBy": "none"},
          {"name": "DEPARTMENT", "dataType": "string", "lineageTag": "f03-inc-dept", "sourceColumn": "DEPARTMENT", "summarizeBy": "none"},
          {"name": "SEVERITY", "dataType": "string", "lineageTag": "f03-inc-sev", "sourceColumn": "SEVERITY", "summarizeBy": "none"}
        ],
        "lineageTag": "f03-tbl-inc",
        "measures": [
          {"name": "Incident Count", "expression": "DISTINCTCOUNT(SAFETY_INCIDENTS[INCIDENT_ID])", "formatString": "0", "lineageTag": "f03-m-inccount"},
          {"name": "Incident Pct of Total", "expression": "DIVIDE([Incident Count], CALCULATE([Incident Count], ALL(SAFETY_INCIDENTS)))", "formatString": "0.0%", "lineageTag": "f03-m-incpct"},
          {"name": "Incident Pct of Dept", "expression": "DIVIDE([Incident Count], CALCULATE([Incident Count], ALLEXCEPT(SAFETY_INCIDENTS, SAFETY_INCIDENTS[DEPARTMENT])))", "formatString": "0.0%", "lineageTag": "f03-m-incpctdept"},
          {"name": "High Severity Incidents", "expression": "CALCULATE([Incident Count], FILTER(SAFETY_INCIDENTS, SAFETY_INCIDENTS[SEVERITY] <> \"Low\"))", "formatString": "0", "lineageTag": "f03-m-highsev"}
        ],
        "partitions": [
          {"name": "SAFETY_INCIDENTS", "mode": "import", "source": {"expression": ["let", "  Source = Snowflake.Databases(\"ymb68310.snowflakecomputing.com\", \"SIGMA_WH\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = \"2.0\"]),", "  #\"Navigation 1\" = Source{[Name = \"CSA\", Kind = \"Database\"]}[Data],", "  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TJ\", Kind = \"Schema\"]}[Data],", "  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"SAFETY_INCIDENTS\", Kind = \"Table\"]}[Data]", "in", "  #\"Navigation 3\""], "type": "m"}}
        ]
      }
    ]
  }
}
