{
  "compatibilityLevel": 1600,
  "model": {
    "annotations": [
      {"name": "PBI_QueryOrder", "value": "[\"EMPLOYEES\",\"ABSENCE_RECORDS\",\"SAFETY_INCIDENTS\",\"DimDate\"]"},
      {"name": "__PBI_TimeIntelligenceEnabled", "value": "1"}
    ],
    "culture": "en-US",
    "dataAccessOptions": {"legacyRedirects": true, "returnErrorValuesAsNull": true},
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {"name": "rel_absence_emp", "fromColumn": "EMPLOYEE_ID", "fromTable": "ABSENCE_RECORDS", "toColumn": "EMPLOYEE_ID", "toTable": "EMPLOYEES"},
      {"name": "rel_incident_emp", "fromColumn": "EMPLOYEE_ID", "fromTable": "SAFETY_INCIDENTS", "toColumn": "EMPLOYEE_ID", "toTable": "EMPLOYEES"},
      {"name": "rel_absence_date", "fromColumn": "DATE", "fromTable": "ABSENCE_RECORDS", "toColumn": "Date", "toTable": "DimDate"},
      {"name": "rel_incident_date", "fromColumn": "DATE", "fromTable": "SAFETY_INCIDENTS", "toColumn": "Date", "toTable": "DimDate"}
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "EMPLOYEES",
        "columns": [
          {"name": "EMPLOYEE_ID", "dataType": "string", "lineageTag": "f02-emp-id", "sourceColumn": "EMPLOYEE_ID", "summarizeBy": "none"},
          {"name": "DEPARTMENT", "dataType": "string", "lineageTag": "f02-emp-dept", "sourceColumn": "DEPARTMENT", "summarizeBy": "none"},
          {"name": "HIRE_DATE", "dataType": "dateTime", "formatString": "Long Date", "lineageTag": "f02-emp-hd", "sourceColumn": "HIRE_DATE", "summarizeBy": "none"},
          {"name": "STATUS", "dataType": "string", "lineageTag": "f02-emp-status", "sourceColumn": "STATUS", "summarizeBy": "none"}
        ],
        "lineageTag": "f02-tbl-emp",
        "measures": [
          {"name": "Headcount", "expression": "COUNTROWS(EMPLOYEES)", "formatString": "0", "lineageTag": "f02-m-hc"}
        ],
        "partitions": [
          {"name": "EMPLOYEES", "mode": "import", "source": {"expression": ["let", "  Source = Snowflake.Databases(\"ymb68310.snowflakecomputing.com\", \"SIGMA_WH\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = \"2.0\"]),", "  #\"Navigation 1\" = Source{[Name = \"CSA\", Kind = \"Database\"]}[Data],", "  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TJ\", Kind = \"Schema\"]}[Data],", "  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"EMPLOYEES\", Kind = \"Table\"]}[Data]", "in", "  #\"Navigation 3\""], "type": "m"}}
        ]
      },
      {
        "name": "ABSENCE_RECORDS",
        "columns": [
          {"name": "ABSENCE_ID", "dataType": "string", "lineageTag": "f02-abs-id", "sourceColumn": "ABSENCE_ID", "summarizeBy": "none"},
          {"name": "EMPLOYEE_ID", "dataType": "string", "lineageTag": "f02-abs-emp", "sourceColumn": "EMPLOYEE_ID", "summarizeBy": "none"},
          {"name": "DATE", "dataType": "dateTime", "formatString": "Long Date", "lineageTag": "f02-abs-date", "sourceColumn": "DATE", "summarizeBy": "none"},
          {"name": "HOURS", "dataType": "double", "lineageTag": "f02-abs-hours", "sourceColumn": "HOURS", "summarizeBy": "sum"}
        ],
        "lineageTag": "f02-tbl-abs",
        "measures": [
          {"name": "Total Absence Hours", "expression": "SUM(ABSENCE_RECORDS[HOURS])", "formatString": "#,0.0", "lineageTag": "f02-m-abshours"},
          {"name": "YTD Absence Hours", "expression": "TOTALYTD(SUM(ABSENCE_RECORDS[HOURS]), DimDate[Date])", "formatString": "#,0.0", "lineageTag": "f02-m-ytdabs"},
          {"name": "MTD Absence Hours", "expression": "TOTALMTD(SUM(ABSENCE_RECORDS[HOURS]), DimDate[Date])", "formatString": "#,0.0", "lineageTag": "f02-m-mtdabs"},
          {"name": "PY Absence Hours", "expression": "CALCULATE(SUM(ABSENCE_RECORDS[HOURS]), SAMEPERIODLASTYEAR(DimDate[Date]))", "formatString": "#,0.0", "lineageTag": "f02-m-pyabs"},
          {"name": "Absence Hours 30d Ago", "expression": "CALCULATE(SUM(ABSENCE_RECORDS[HOURS]), DATEADD(DimDate[Date], -30, DAY))", "formatString": "#,0.0", "lineageTag": "f02-m-abs30d"},
          {"name": "YoY Absence Hours Pct", "expression": "DIVIDE([Total Absence Hours] - [PY Absence Hours], [PY Absence Hours])", "formatString": "0.0%", "lineageTag": "f02-m-yoyabs"}
        ],
        "partitions": [
          {"name": "ABSENCE_RECORDS", "mode": "import", "source": {"expression": ["let", "  Source = Snowflake.Databases(\"ymb68310.snowflakecomputing.com\", \"SIGMA_WH\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = \"2.0\"]),", "  #\"Navigation 1\" = Source{[Name = \"CSA\", Kind = \"Database\"]}[Data],", "  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TJ\", Kind = \"Schema\"]}[Data],", "  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"ABSENCE_RECORDS\", Kind = \"Table\"]}[Data]", "in", "  #\"Navigation 3\""], "type": "m"}}
        ]
      },
      {
        "name": "SAFETY_INCIDENTS",
        "columns": [
          {"name": "INCIDENT_ID", "dataType": "string", "lineageTag": "f02-inc-id", "sourceColumn": "INCIDENT_ID", "summarizeBy": "none"},
          {"name": "EMPLOYEE_ID", "dataType": "string", "lineageTag": "f02-inc-emp", "sourceColumn": "EMPLOYEE_ID", "summarizeBy": "none"},
          {"name": "DATE", "dataType": "dateTime", "formatString": "Long Date", "lineageTag": "f02-inc-date", "sourceColumn": "DATE", "summarizeBy": "none"},
          {"name": "SEVERITY", "dataType": "string", "lineageTag": "f02-inc-sev", "sourceColumn": "SEVERITY", "summarizeBy": "none"}
        ],
        "lineageTag": "f02-tbl-inc",
        "measures": [
          {"name": "Incident Count", "expression": "DISTINCTCOUNT(SAFETY_INCIDENTS[INCIDENT_ID])", "formatString": "0", "lineageTag": "f02-m-inccount"},
          {"name": "PY Incident Count", "expression": "CALCULATE(DISTINCTCOUNT(SAFETY_INCIDENTS[INCIDENT_ID]), SAMEPERIODLASTYEAR(DimDate[Date]))", "formatString": "0", "lineageTag": "f02-m-pyinc"},
          {"name": "YTD Incident Count", "expression": "TOTALYTD(DISTINCTCOUNT(SAFETY_INCIDENTS[INCIDENT_ID]), DimDate[Date])", "formatString": "0", "lineageTag": "f02-m-ytdinc"},
          {"name": "Incident MoM Delta", "expression": "DISTINCTCOUNT(SAFETY_INCIDENTS[INCIDENT_ID]) - CALCULATE(DISTINCTCOUNT(SAFETY_INCIDENTS[INCIDENT_ID]), DATEADD(DimDate[Date], -1, MONTH))", "formatString": "0", "lineageTag": "f02-m-incmom"}
        ],
        "partitions": [
          {"name": "SAFETY_INCIDENTS", "mode": "import", "source": {"expression": ["let", "  Source = Snowflake.Databases(\"ymb68310.snowflakecomputing.com\", \"SIGMA_WH\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = \"2.0\"]),", "  #\"Navigation 1\" = Source{[Name = \"CSA\", Kind = \"Database\"]}[Data],", "  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TJ\", Kind = \"Schema\"]}[Data],", "  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"SAFETY_INCIDENTS\", Kind = \"Table\"]}[Data]", "in", "  #\"Navigation 3\""], "type": "m"}}
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {"name": "Date", "dataType": "dateTime", "isKey": true, "formatString": "Long Date", "lineageTag": "f02-dd-date", "sourceColumn": "[Date]", "summarizeBy": "none"},
          {"name": "Year", "dataType": "int64", "isDataTypeInferred": true, "lineageTag": "f02-dd-year", "sourceColumn": "[Year]", "summarizeBy": "none"},
          {"name": "MonthNo", "dataType": "int64", "isDataTypeInferred": true, "lineageTag": "f02-dd-monthno", "sourceColumn": "[MonthNo]", "summarizeBy": "none"},
          {"name": "Month", "dataType": "string", "isDataTypeInferred": true, "lineageTag": "f02-dd-month", "sourceColumn": "[Month]", "summarizeBy": "none", "sortByColumn": "MonthNo"},
          {"name": "QuarterNo", "dataType": "int64", "isDataTypeInferred": true, "lineageTag": "f02-dd-qno", "sourceColumn": "[QuarterNo]", "summarizeBy": "none"},
          {"name": "Quarter", "dataType": "string", "isDataTypeInferred": true, "lineageTag": "f02-dd-q", "sourceColumn": "[Quarter]", "summarizeBy": "none"}
        ],
        "lineageTag": "f02-tbl-dimdate",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": "ADDCOLUMNS(CALENDAR(DATE(2018,1,1), DATE(2026,12,31)), \"Year\", YEAR([Date]), \"MonthNo\", MONTH([Date]), \"Month\", FORMAT([Date], \"MMM\"), \"QuarterNo\", QUARTER([Date]), \"Quarter\", \"Q\" & QUARTER([Date]))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}
