{
  "compatibilityLevel": 1600,
  "model": {
    "annotations": [
      {"name": "PBI_QueryOrder", "value": "[\"EMPLOYEES\",\"ABSENCE_RECORDS\",\"SalaryBands\"]"},
      {"name": "__PBI_TimeIntelligenceEnabled", "value": "0"}
    ],
    "culture": "en-US",
    "dataAccessOptions": {"legacyRedirects": true, "returnErrorValuesAsNull": true},
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "relationships": [
      {"name": "rel_absence_emp", "fromColumn": "EMPLOYEE_ID", "fromTable": "ABSENCE_RECORDS", "toColumn": "EMPLOYEE_ID", "toTable": "EMPLOYEES"}
    ],
    "tables": [
      {
        "name": "EMPLOYEES",
        "columns": [
          {"name": "EMPLOYEE_ID", "dataType": "string", "lineageTag": "f07-emp-id", "sourceColumn": "EMPLOYEE_ID", "summarizeBy": "none"},
          {"name": "FIRST_NAME", "dataType": "string", "lineageTag": "f07-emp-fn", "sourceColumn": "FIRST_NAME", "summarizeBy": "none"},
          {"name": "LAST_NAME", "dataType": "string", "lineageTag": "f07-emp-ln", "sourceColumn": "LAST_NAME", "summarizeBy": "none"},
          {"name": "EMAIL", "dataType": "string", "lineageTag": "f07-emp-email", "sourceColumn": "EMAIL", "summarizeBy": "none"},
          {"name": "DEPARTMENT", "dataType": "string", "lineageTag": "f07-emp-dept", "sourceColumn": "DEPARTMENT", "summarizeBy": "none"},
          {"name": "ROLE", "dataType": "string", "lineageTag": "f07-emp-role", "sourceColumn": "ROLE", "summarizeBy": "none"},
          {"name": "LOCATION", "dataType": "string", "lineageTag": "f07-emp-loc", "sourceColumn": "LOCATION", "summarizeBy": "none"},
          {"name": "STATE", "dataType": "string", "lineageTag": "f07-emp-state", "sourceColumn": "STATE", "summarizeBy": "none"},
          {"name": "CITY", "dataType": "string", "lineageTag": "f07-emp-city", "sourceColumn": "CITY", "summarizeBy": "none"},
          {"name": "HIRE_DATE", "dataType": "dateTime", "formatString": "Long Date", "lineageTag": "f07-emp-hd", "sourceColumn": "HIRE_DATE", "summarizeBy": "none"},
          {"name": "STATUS", "dataType": "string", "lineageTag": "f07-emp-status", "sourceColumn": "STATUS", "summarizeBy": "none"},
          {"name": "MANAGER_ID", "dataType": "string", "lineageTag": "f07-emp-mgr", "sourceColumn": "MANAGER_ID", "summarizeBy": "none"},
          {"name": "ANNUAL_SALARY", "dataType": "double", "lineageTag": "f07-emp-sal", "sourceColumn": "ANNUAL_SALARY", "summarizeBy": "sum"},
          {"name": "EMPLOYMENT_TYPE", "dataType": "string", "lineageTag": "f07-emp-et", "sourceColumn": "EMPLOYMENT_TYPE", "summarizeBy": "none"},
          {"name": "SHIFT", "dataType": "string", "lineageTag": "f07-emp-shift", "sourceColumn": "SHIFT", "summarizeBy": "none"},
          {
            "name": "Email Domain",
            "type": "calculated",
            "expression": "MID(EMPLOYEES[EMAIL], SEARCH(\"@\", EMPLOYEES[EMAIL]) + 1, LEN(EMPLOYEES[EMAIL]))",
            "dataType": "string",
            "lineageTag": "f07-cc-emaildomain",
            "summarizeBy": "none"
          },
          {
            "name": "Role Family",
            "type": "calculated",
            "expression": "SUBSTITUTE(SUBSTITUTE(EMPLOYEES[ROLE], \"Sr. \", \"\"), \"Manager\", \"Mgmt\")",
            "dataType": "string",
            "lineageTag": "f07-cc-rolefamily",
            "summarizeBy": "none"
          },
          {
            "name": "Dept-Role Key",
            "type": "calculated",
            "expression": "COMBINEVALUES(\" | \", EMPLOYEES[DEPARTMENT], EMPLOYEES[ROLE])",
            "dataType": "string",
            "lineageTag": "f07-cc-deptrolekey",
            "summarizeBy": "none"
          },
          {
            "name": "Salary Rank In Dept",
            "type": "calculated",
            "expression": "COUNTROWS(FILTER(EMPLOYEES, EMPLOYEES[DEPARTMENT] = EARLIER(EMPLOYEES[DEPARTMENT]) && EMPLOYEES[ANNUAL_SALARY] > EARLIER(EMPLOYEES[ANNUAL_SALARY]))) + 1",
            "dataType": "int64",
            "lineageTag": "f07-cc-salrankdept",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f07-tbl-emp",
        "measures": [
          {"name": "Headcount", "expression": "COUNTROWS(EMPLOYEES)", "formatString": "0", "lineageTag": "f07-m-hc"},
          {"name": "Total Salary", "expression": "SUM(EMPLOYEES[ANNUAL_SALARY])", "formatString": "\\$#,0", "lineageTag": "f07-m-totsal"},
          {"name": "Median Salary", "expression": "MEDIANX(EMPLOYEES, EMPLOYEES[ANNUAL_SALARY])", "formatString": "\\$#,0", "lineageTag": "f07-m-mediansal"},
          {"name": "P90 Salary", "expression": "PERCENTILEX.INC(EMPLOYEES, EMPLOYEES[ANNUAL_SALARY], 0.9)", "formatString": "\\$#,0", "lineageTag": "f07-m-p90sal"},
          {"name": "P10 Salary", "expression": "PERCENTILEX.INC(EMPLOYEES, EMPLOYEES[ANNUAL_SALARY], 0.1)", "formatString": "\\$#,0", "lineageTag": "f07-m-p10sal"},
          {"name": "Salary StdDev", "expression": "STDEVX.P(EMPLOYEES, EMPLOYEES[ANNUAL_SALARY])", "formatString": "\\$#,0", "lineageTag": "f07-m-salstdev"},
          {"name": "Salary Variance", "expression": "VARX.P(EMPLOYEES, EMPLOYEES[ANNUAL_SALARY])", "formatString": "#,0", "lineageTag": "f07-m-salvar"},
          {"name": "Salary GeoMean", "expression": "GEOMEANX(EMPLOYEES, EMPLOYEES[ANNUAL_SALARY])", "formatString": "\\$#,0", "lineageTag": "f07-m-salgeomean"},
          {"name": "Salary Spread P90-P10", "expression": "[P90 Salary] - [P10 Salary]", "formatString": "\\$#,0", "lineageTag": "f07-m-salspread"},
          {"name": "Distinct Roles", "expression": "DISTINCTCOUNTNOBLANK(EMPLOYEES[ROLE])", "formatString": "0", "lineageTag": "f07-m-distroles"},
          {
            "name": "Roles In Dept",
            "expression": "CONCATENATEX(VALUES(EMPLOYEES[ROLE]), EMPLOYEES[ROLE], \", \", EMPLOYEES[ROLE], ASC)",
            "lineageTag": "f07-m-rolesindept"
          },
          {
            "name": "Top 5 Role Salary",
            "expression": "SUMX(TOPN(5, VALUES(EMPLOYEES[ROLE]), [Total Salary], DESC), [Total Salary])",
            "formatString": "\\$#,0",
            "lineageTag": "f07-m-top5role"
          },
          {
            "name": "Selected Dept Label",
            "expression": "IF(HASONEVALUE(EMPLOYEES[DEPARTMENT]), SELECTEDVALUE(EMPLOYEES[DEPARTMENT]), \"All Departments\")",
            "lineageTag": "f07-m-seldept"
          },
          {
            "name": "Salary vs Company Median",
            "expression": "VAR DeptMed = MEDIANX(EMPLOYEES, EMPLOYEES[ANNUAL_SALARY])\nVAR CoMed = CALCULATE(MEDIANX(EMPLOYEES, EMPLOYEES[ANNUAL_SALARY]), REMOVEFILTERS(EMPLOYEES))\nRETURN DIVIDE(DeptMed - CoMed, CoMed)",
            "formatString": "0.0%",
            "lineageTag": "f07-m-salvscomed"
          },
          {
            "name": "Pct In Selected Bands",
            "expression": "VAR Picked = CALCULATETABLE(VALUES(SalaryBands[Band]), KEEPFILTERS(SalaryBands))\nRETURN DIVIDE(CALCULATE([Headcount], TREATAS(Picked, SalaryBands[Band])), CALCULATE([Headcount], REMOVEFILTERS(SalaryBands)))",
            "formatString": "0.0%",
            "lineageTag": "f07-m-pctbands"
          },
          {
            "name": "Mgmt Headcount",
            "expression": "COALESCE(CALCULATE([Headcount], KEEPFILTERS(SEARCH(\"Manager\", EMPLOYEES[ROLE], 1, 0) > 0)), 0)",
            "formatString": "0",
            "lineageTag": "f07-m-mgmthc"
          }
        ],
        "partitions": [
          {"name": "EMPLOYEES", "mode": "import", "source": {"expression": ["let", "  Source = Snowflake.Databases(\"ymb68310.snowflakecomputing.com\", \"SIGMA_WH\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = \"2.0\"]),", "  #\"Navigation 1\" = Source{[Name = \"CSA\", Kind = \"Database\"]}[Data],", "  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TJ\", Kind = \"Schema\"]}[Data],", "  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"EMPLOYEES\", Kind = \"Table\"]}[Data]", "in", "  #\"Navigation 3\""], "type": "m"}}
        ]
      },
      {
        "name": "ABSENCE_RECORDS",
        "columns": [
          {"name": "ABSENCE_ID", "dataType": "string", "lineageTag": "f07-abs-id", "sourceColumn": "ABSENCE_ID", "summarizeBy": "none"},
          {"name": "EMPLOYEE_ID", "dataType": "string", "lineageTag": "f07-abs-emp", "sourceColumn": "EMPLOYEE_ID", "summarizeBy": "none"},
          {"name": "DATE", "dataType": "dateTime", "formatString": "Long Date", "lineageTag": "f07-abs-date", "sourceColumn": "DATE", "summarizeBy": "none"},
          {"name": "ABSENCE_TYPE", "dataType": "string", "lineageTag": "f07-abs-type", "sourceColumn": "ABSENCE_TYPE", "summarizeBy": "none"},
          {"name": "HOURS", "dataType": "double", "lineageTag": "f07-abs-hours", "sourceColumn": "HOURS", "summarizeBy": "sum"},
          {"name": "DEPARTMENT", "dataType": "string", "lineageTag": "f07-abs-dept", "sourceColumn": "DEPARTMENT", "summarizeBy": "none"}
        ],
        "lineageTag": "f07-tbl-abs",
        "measures": [
          {"name": "Total Absence Hours", "expression": "SUM(ABSENCE_RECORDS[HOURS])", "formatString": "#,0.0", "lineageTag": "f07-m-abshours"},
          {
            "name": "Absence Hours (High Earners)",
            "expression": "VAR HighEarners = CALCULATETABLE(VALUES(EMPLOYEES[EMPLOYEE_ID]), FILTER(ALL(EMPLOYEES), EMPLOYEES[ANNUAL_SALARY] >= [P90 Salary]))\nRETURN CALCULATE([Total Absence Hours], TREATAS(HighEarners, ABSENCE_RECORDS[EMPLOYEE_ID]))",
            "formatString": "#,0.0",
            "lineageTag": "f07-m-abshigh"
          }
        ],
        "partitions": [
          {"name": "ABSENCE_RECORDS", "mode": "import", "source": {"expression": ["let", "  Source = Snowflake.Databases(\"ymb68310.snowflakecomputing.com\", \"SIGMA_WH\", [Role = null, CreateNavigationProperties = null, ConnectionTimeout = null, CommandTimeout = null, Implementation = \"2.0\"]),", "  #\"Navigation 1\" = Source{[Name = \"CSA\", Kind = \"Database\"]}[Data],", "  #\"Navigation 2\" = #\"Navigation 1\"{[Name = \"TJ\", Kind = \"Schema\"]}[Data],", "  #\"Navigation 3\" = #\"Navigation 2\"{[Name = \"ABSENCE_RECORDS\", Kind = \"Table\"]}[Data]", "in", "  #\"Navigation 3\""], "type": "m"}}
        ]
      },
      {
        "name": "SalaryBands",
        "columns": [
          {"name": "BandFloor", "dataType": "int64", "type": "calculatedTableColumn", "sourceColumn": "BandFloor", "lineageTag": "f07-sb-floor", "summarizeBy": "none"},
          {"name": "Band", "dataType": "string", "type": "calculatedTableColumn", "sourceColumn": "Band", "lineageTag": "f07-sb-band", "summarizeBy": "none"}
        ],
        "lineageTag": "f07-tbl-bands",
        "partitions": [
          {
            "name": "SalaryBands",
            "mode": "import",
            "source": {
              "expression": "ADDCOLUMNS(SELECTCOLUMNS(GENERATESERIES(40000, 200000, 40000), \"BandFloor\", [Value]), \"Band\", \"$\" & FORMAT([BandFloor]/1000, \"0\") & \"k+\")",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}
